name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [25.3]
        elixir: [1.14.x]
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: elixir
          package-name: za_national_id

      - name: publish to hex
        if: ${{ steps.release.outputs.release_created }}
        env:
          HEX_API_KEY: ${{secrets.HEX_API_KEY}}
        run: |
          mix hex.publish --yes
